services:
  db:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: introds
      MYSQL_ROOT_PASSWORD: lanzillotta
    volumes:
      - ../sql/init.sql:/docker-entrypoint-initdb.d/init.sql
